// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    FlatContainerV1: typeof import('./src/components/V1/FlatContainerV1.vue')['default']
    FloatContainer: typeof import('./src/components/FloatContainer.vue')['default']
    FloatContainerOld: typeof import('./src/components/old/FloatContainerOld.vue')['default']
    FloatProxy: typeof import('./src/components/FloatProxy.vue')['default']
    FloatProxyOld: typeof import('./src/components/old/FloatProxyOld.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    TheImage: typeof import('./src/components/old/TheImage.vue')['default']
    TheImageNew: typeof import('./src/components/TheImageNew.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}

export { }
